# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'FF_HUD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FF_HUD
  
  pod 'MBProgressHUD'

	pod 'XWHUDManager'
  

  target 'FF_HUDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FF_HUDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
